# Generated by Django 4.1.3 on 2023-02-02 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_alter_search_use_full'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='h',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='search',
            name='w',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='search',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='search',
            name='y',
            field=models.IntegerField(default=0),
        ),
    ]
